---
title: "MAF-900: Final Assessment Replication"
author: 'Group: Ruowen and Sohail'
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
  word_document: default
editor_options: 
  markdown: 
    wrap: 72
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
library(knitr)
library(tinytex)



```

# Introduction

This is group report based on the replication of a paper titled **"Risk
Return and Equilibrium: Empirical Tests"** also know as **Fama-MacBeth
(1973) regression**. We replicated table 1 to table 4 of the original
paper and extended the sample period to December, 2022.

# Data and Replication methodology

The data for this replication are monthly return of stocks traded on New
York Stock Exchange from January 1926 to December 2022. The data is from
CRSP. The risk-free rate is from French's data library.

The basic methodology follows Fama and MacBeth (1973). To replicate the
**table 1**, we separate the whole sample period into the subperiod
using the same criteria as the original paper. In sum, we totally have
22 subperiods. For each period, we use the same criteria as the original
paper to calculate the number of stocks. One thing we do which is not
explicitly pointed out in the paper is that we filter all the
observations that have missing values in return.

After replicating table 1, we save the permno numbers of stocks that
meet data requirements into the next stage.

Before replicating **table 2**, we have to first estimate the betas of
each stock and form portfolio in the "Portfolio formation period". We
run the time series regression for each stock to estimate the beta, and
then ranking the beta to form the 20 portfolios in each period. In the
step, when we estimate the beta, we run the market model:

${R_{it} = a_t + \beta^i R_{mt} + \epsilon_{it}}$

where the market return in the Fisher's Arithmetic Index, which is the
equally weighted average of the returns on all stocks listed on NYSE.
After we form the portfolio, we start to estimate the portfolio beta and
create table 2. Specifically, we run the market model for each stock
over the estimation period, and calculate the portfolio's beta by taking
the average.

With the estimated beta, we move the next stage: **creating table 3**.

At first, as the betas have to updated annually, we first rerun the beta
estimation for the portfolio. For example, in the first sample period,
we run the four regressions with data from 1930 (the starting year in
estimation period) to 1935, 1936, and 1937 (one year before the end the
testing period) to have annually updated betas. After that, following
regression model specified in the paper, we run four models (describe as
from Panel A to Panel D in paper 3) to get the time series of gammas.
After that, we could create the statistics in table 3 by using those
time series. Similar to original paper, we present the results for the
whole sample period, 7 longer period with 10 years with one exception of
the last period, the 22 testing period specified in the table 1.

For **table 4**, we include the risk-free rate into the dataset to
calculate those summary statistics. Also the statistics which are
presented in the table 3 are those from the panel A regression. For both
Table 3 and Table 4, when we calculate the t-statistics, we follow the
adjustment mentioned in the original paper.

Table 1 demonstrates the summary of total securities available for the
first month of the testing period and the number of securities that meet
the data requirement according to the original paper. Our table 1
replication closely follow the original paper except the first period
(1926-29), where we only found 264 securities meet the data requirement.
We suspect that this disparity arise due to CRSP database update during
that sample. Overall, the number of securities exhibit upward trend over
time.

**Table 1: Portfolio Formation, Estimation And Testing Periods**

| **Portfolio Formation Period** | **Initial Formation Period** | **Testing Period** | **No. of Securities Available** | **No. of Securities Data Re quirement** |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
|            1926-29             |           1930-34            |      1935-38       |               670               |                   264                   |
|            1927-33             |           1934-38            |      1939-42       |               731               |                   493                   |
|            1931-37             |           1938-42            |      1943-46       |               753               |                   554                   |
|            1935-41             |           1942-46            |      1947-50       |               850               |                   640                   |
|            1939-45             |           1946-50            |      1951-54       |               944               |                   697                   |
|            1943-49             |           1950-54            |      1955-58       |               983               |                   749                   |
|            1947-53             |           1954-58            |      1959-62       |               998               |                   779                   |
|            1951-57             |           1958-62            |      1963-66       |              1265               |                   780                   |
|            1955-61             |           1962-66            |      1967-70       |              1385               |                   770                   |
|            1959-65             |           1966-70            |      1971-74       |              1509               |                   750                   |
|            1963-69             |           1970-74            |      1975-78       |              2042               |                  1040                   |
|            1967-73             |           1974-78            |      1979-82       |              1994               |                  1131                   |
|            1971-77             |           1978-82            |      1983-86       |              1920               |                  1577                   |
|            1975-81             |           1982-86            |      1987-90       |              2060               |                  1417                   |
|            1979-85             |           1986-90            |      1991-94       |              2178               |                  1290                   |
|            1983-89             |           1990-94            |      1995-98       |              2915               |                  1420                   |
|            1987-93             |           1994-98            |     1999-2002      |              3004               |                  1496                   |
|            1991-97             |          1998-2002           |      2003-06       |              2590               |                  1580                   |
|           1995-2001            |           2002-06            |      2007-10       |              2618               |                  1674                   |
|           1999-2005            |           2006-10            |      2011-14       |              2467               |                  1595                   |
|            2003-09             |           2010-14            |      2015-18       |              2617               |                  1697                   |
|            2007-13             |           2014-18            |      2019-22       |              2444               |                  1605                   |

To replicate and present table 2, we split the the table into two part
for each estimation period. The original paper depicted sample statistic
for four estimation periods, which we included. To show the extended
sample summary statistic of table two, we choose the four estimation
period **(1990-94, 1998-2002, 2006-10 and 2014-18)**, respectively. The
replication results are found very close to the original paper.

# Table 2: Sample Statistics For Selected Estimation Periods

<center>

Portfolios For Estimation 1934-38

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.412 | 0.565 | 0.537 | 0.660 | 0.723 | 0.753 | 0.903 | 0.967 | 0.954 | 1.033 |
| s_beta    | 0.026 | 0.029 | 0.025 | 0.031 | 0.025 | 0.024 | 0.029 | 0.033 | 0.027 | 0.027 |
| Rsquared  | 0.815 | 0.869 | 0.887 | 0.887 | 0.937 | 0.943 | 0.944 | 0.938 | 0.955 | 0.962 |
| s_Rp      | 0.048 | 0.064 | 0.060 | 0.074 | 0.079 | 0.082 | 0.098 | 0.105 | 0.103 | 0.111 |
| s_ep      | 0.021 | 0.023 | 0.020 | 0.025 | 0.020 | 0.020 | 0.023 | 0.026 | 0.022 | 0.022 |
| sp_ei     | 0.067 | 0.078 | 0.071 | 0.077 | 0.084 | 0.077 | 0.103 | 0.113 | 0.096 | 0.091 |
| ratio     | 0.309 | 0.295 | 0.284 | 0.324 | 0.237 | 0.253 | 0.224 | 0.233 | 0.228 | 0.237 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.137 | 1.122 | 1.200 | 1.232 | 1.212 | 1.317 | 1.324 | 1.380 | 1.404 | 1.519 |
| s_beta    | 0.031 | 0.034 | 0.039 | 0.031 | 0.037 | 0.033 | 0.044 | 0.046 | 0.043 | 0.064 |
| Rsquared  | 0.960 | 0.950 | 0.943 | 0.964 | 0.948 | 0.965 | 0.940 | 0.940 | 0.948 | 0.906 |
| s_Rp      | 0.122 | 0.121 | 0.130 | 0.132 | 0.131 | 0.141 | 0.144 | 0.150 | 0.152 | 0.168 |
| s_ep      | 0.025 | 0.027 | 0.031 | 0.025 | 0.030 | 0.026 | 0.035 | 0.037 | 0.035 | 0.052 |
| sp_ei     | 0.108 | 0.123 | 0.127 | 0.131 | 0.122 | 0.128 | 0.123 | 0.137 | 0.138 | 0.175 |
| ratio     | 0.227 | 0.222 | 0.244 | 0.190 | 0.246 | 0.206 | 0.288 | 0.270 | 0.250 | 0.294 |

# Table 2: continue..

<center>

Portfolios For Estimation 1942-46

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.457 | 0.530 | 0.602 | 0.604 | 0.731 | 0.695 | 0.794 | 0.774 | 0.769 | 0.858 |
| s_beta    | 0.045 | 0.039 | 0.047 | 0.037 | 0.030 | 0.035 | 0.041 | 0.030 | 0.035 | 0.036 |
| Rsquared  | 0.641 | 0.757 | 0.740 | 0.818 | 0.913 | 0.875 | 0.869 | 0.922 | 0.894 | 0.909 |
| s_Rp      | 0.034 | 0.037 | 0.042 | 0.040 | 0.046 | 0.045 | 0.051 | 0.048 | 0.049 | 0.054 |
| s_ep      | 0.021 | 0.018 | 0.021 | 0.017 | 0.014 | 0.016 | 0.019 | 0.014 | 0.016 | 0.016 |
| sp_ei     | 0.054 | 0.052 | 0.062 | 0.055 | 0.057 | 0.063 | 0.063 | 0.059 | 0.061 | 0.066 |
| ratio     | 0.382 | 0.349 | 0.343 | 0.311 | 0.240 | 0.252 | 0.292 | 0.228 | 0.263 | 0.246 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.929 | 1.021 | 1.033 | 1.086 | 1.173 | 1.426 | 1.412 | 1.351 | 1.763 | 1.593 |
| s_beta    | 0.033 | 0.033 | 0.037 | 0.041 | 0.043 | 0.038 | 0.055 | 0.046 | 0.081 | 0.088 |
| Rsquared  | 0.930 | 0.943 | 0.930 | 0.924 | 0.928 | 0.961 | 0.920 | 0.936 | 0.891 | 0.851 |
| s_Rp      | 0.058 | 0.063 | 0.064 | 0.068 | 0.073 | 0.087 | 0.088 | 0.084 | 0.112 | 0.104 |
| s_ep      | 0.015 | 0.015 | 0.017 | 0.019 | 0.020 | 0.017 | 0.025 | 0.021 | 0.037 | 0.040 |
| sp_ei     | 0.069 | 0.073 | 0.085 | 0.080 | 0.079 | 0.100 | 0.093 | 0.092 | 0.125 | 0.115 |
| ratio     | 0.222 | 0.206 | 0.201 | 0.232 | 0.248 | 0.172 | 0.268 | 0.230 | 0.296 | 0.349 |

# Table 2: continue..

<center>

Portfolios For Estimation 1950-54

<center>

# Portfolios For Estimation 1950-54

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.430 | 0.572 | 0.729 | 0.734 | 0.817 | 0.756 | 0.929 | 0.983 | 0.982 | 0.987 |
| s_beta    | 0.041 | 0.049 | 0.047 | 0.042 | 0.036 | 0.038 | 0.050 | 0.034 | 0.035 | 0.031 |
| Rsquared  | 0.657 | 0.698 | 0.807 | 0.839 | 0.897 | 0.870 | 0.855 | 0.936 | 0.932 | 0.947 |
| s_Rp      | 0.019 | 0.025 | 0.029 | 0.029 | 0.031 | 0.029 | 0.036 | 0.037 | 0.037 | 0.037 |
| s_ep      | 0.011 | 0.014 | 0.013 | 0.012 | 0.010 | 0.011 | 0.014 | 0.009 | 0.010 | 0.008 |
| sp_ei     | 0.039 | 0.044 | 0.046 | 0.051 | 0.048 | 0.049 | 0.053 | 0.050 | 0.057 | 0.053 |
| ratio     | 0.286 | 0.314 | 0.282 | 0.229 | 0.209 | 0.216 | 0.264 | 0.188 | 0.169 | 0.159 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.086 | 1.200 | 1.078 | 1.205 | 1.131 | 1.284 | 1.228 | 1.330 | 1.416 | 1.531 |
| s_beta    | 0.034 | 0.049 | 0.036 | 0.052 | 0.039 | 0.048 | 0.045 | 0.047 | 0.062 | 0.086 |
| Rsquared  | 0.946 | 0.911 | 0.940 | 0.903 | 0.935 | 0.926 | 0.928 | 0.932 | 0.899 | 0.847 |
| s_Rp      | 0.041 | 0.046 | 0.040 | 0.046 | 0.042 | 0.048 | 0.046 | 0.050 | 0.054 | 0.060 |
| s_ep      | 0.009 | 0.014 | 0.010 | 0.014 | 0.011 | 0.013 | 0.012 | 0.013 | 0.017 | 0.024 |
| sp_ei     | 0.058 | 0.059 | 0.059 | 0.065 | 0.063 | 0.063 | 0.062 | 0.068 | 0.072 | 0.089 |
| ratio     | 0.161 | 0.231 | 0.167 | 0.222 | 0.173 | 0.210 | 0.199 | 0.191 | 0.239 | 0.267 |

# Table 2: continue..

<center>

Portfolios For Estimation 1958-62

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.648 | 0.630 | 0.696 | 0.745 | 0.872 | 0.857 | 0.945 | 0.998 | 0.960 | 0.903 |
| s_beta    | 0.045 | 0.049 | 0.041 | 0.047 | 0.048 | 0.032 | 0.032 | 0.034 | 0.038 | 0.038 |
| Rsquared  | 0.779 | 0.738 | 0.831 | 0.814 | 0.849 | 0.924 | 0.938 | 0.936 | 0.918 | 0.908 |
| s_Rp      | 0.031 | 0.031 | 0.033 | 0.035 | 0.041 | 0.038 | 0.042 | 0.044 | 0.043 | 0.041 |
| s_ep      | 0.015 | 0.016 | 0.013 | 0.015 | 0.016 | 0.011 | 0.010 | 0.011 | 0.012 | 0.012 |
| sp_ei     | 0.050 | 0.050 | 0.052 | 0.055 | 0.065 | 0.060 | 0.064 | 0.069 | 0.069 | 0.061 |
| ratio     | 0.297 | 0.324 | 0.258 | 0.278 | 0.242 | 0.175 | 0.162 | 0.163 | 0.179 | 0.201 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.082 | 0.966 | 1.042 | 1.048 | 0.992 | 1.141 | 1.137 | 1.118 | 1.229 | 1.410 |
| s_beta    | 0.043 | 0.028 | 0.035 | 0.038 | 0.035 | 0.045 | 0.045 | 0.044 | 0.050 | 0.072 |
| Rsquared  | 0.915 | 0.952 | 0.937 | 0.930 | 0.933 | 0.918 | 0.916 | 0.918 | 0.912 | 0.867 |
| s_Rp      | 0.048 | 0.042 | 0.046 | 0.047 | 0.044 | 0.051 | 0.051 | 0.050 | 0.055 | 0.065 |
| s_ep      | 0.014 | 0.009 | 0.012 | 0.012 | 0.011 | 0.015 | 0.015 | 0.014 | 0.016 | 0.024 |
| sp_ei     | 0.075 | 0.062 | 0.064 | 0.065 | 0.061 | 0.072 | 0.076 | 0.069 | 0.067 | 0.078 |
| ratio     | 0.187 | 0.149 | 0.180 | 0.188 | 0.188 | 0.204 | 0.195 | 0.208 | 0.244 | 0.302 |

# Table 2: continue..

<center>

Portfolios For Estimation 1990-94

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.326 | 0.389 | 0.470 | 0.539 | 0.764 | 0.850 | 0.725 | 0.909 | 0.997 | 0.941 |
| s_beta    | 0.064 | 0.056 | 0.057 | 0.043 | 0.051 | 0.038 | 0.040 | 0.042 | 0.048 | 0.046 |
| Rsquared  | 0.312 | 0.453 | 0.538 | 0.734 | 0.796 | 0.895 | 0.847 | 0.892 | 0.880 | 0.877 |
| s_Rp      | 0.024 | 0.024 | 0.026 | 0.026 | 0.035 | 0.037 | 0.032 | 0.039 | 0.043 | 0.041 |
| s_ep      | 0.020 | 0.017 | 0.018 | 0.013 | 0.016 | 0.012 | 0.013 | 0.013 | 0.015 | 0.014 |
| sp_ei     | 0.048 | 0.057 | 0.071 | 0.077 | 0.090 | 0.078 | 0.078 | 0.077 | 0.083 | 0.082 |
| ratio     | 0.411 | 0.308 | 0.252 | 0.172 | 0.176 | 0.151 | 0.160 | 0.167 | 0.182 | 0.175 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.029 | 1.013 | 0.963 | 1.031 | 1.214 | 1.166 | 1.199 | 1.356 | 1.471 | 1.598 |
| s_beta    | 0.044 | 0.050 | 0.040 | 0.046 | 0.045 | 0.053 | 0.050 | 0.059 | 0.076 | 0.072 |
| Rsquared  | 0.902 | 0.877 | 0.908 | 0.895 | 0.927 | 0.891 | 0.909 | 0.901 | 0.867 | 0.894 |
| s_Rp      | 0.044 | 0.044 | 0.041 | 0.044 | 0.051 | 0.050 | 0.051 | 0.058 | 0.064 | 0.069 |
| s_ep      | 0.014 | 0.015 | 0.012 | 0.014 | 0.014 | 0.017 | 0.015 | 0.018 | 0.024 | 0.022 |
| sp_ei     | 0.093 | 0.084 | 0.081 | 0.086 | 0.099 | 0.096 | 0.107 | 0.110 | 0.136 | 0.137 |
| ratio     | 0.148 | 0.184 | 0.155 | 0.166 | 0.140 | 0.174 | 0.145 | 0.166 | 0.173 | 0.164 |

# Table 2: continue..

<center>

Portfolios For Estimation 1998-2002

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.455 | 0.218 | 0.328 | 0.375 | 0.491 | 0.590 | 0.726 | 0.828 | 0.950 | 0.952 |
| s_beta    | 0.050 | 0.046 | 0.050 | 0.046 | 0.041 | 0.038 | 0.052 | 0.042 | 0.044 | 0.048 |
| Rsquared  | 0.591 | 0.281 | 0.422 | 0.537 | 0.710 | 0.808 | 0.769 | 0.870 | 0.889 | 0.873 |
| s_Rp      | 0.028 | 0.020 | 0.024 | 0.025 | 0.028 | 0.031 | 0.040 | 0.043 | 0.048 | 0.049 |
| s_ep      | 0.018 | 0.017 | 0.018 | 0.017 | 0.015 | 0.014 | 0.019 | 0.015 | 0.016 | 0.017 |
| sp_ei     | 0.074 | 0.050 | 0.061 | 0.063 | 0.073 | 0.075 | 0.095 | 0.095 | 0.091 | 0.096 |
| ratio     | 0.246 | 0.333 | 0.302 | 0.264 | 0.206 | 0.183 | 0.201 | 0.161 | 0.177 | 0.180 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.030 | 1.107 | 1.114 | 1.039 | 1.104 | 1.178 | 1.323 | 1.275 | 1.455 | 1.496 |
| s_beta    | 0.053 | 0.046 | 0.040 | 0.047 | 0.049 | 0.041 | 0.039 | 0.050 | 0.050 | 0.080 |
| Rsquared  | 0.868 | 0.908 | 0.930 | 0.896 | 0.897 | 0.933 | 0.953 | 0.917 | 0.935 | 0.858 |
| s_Rp      | 0.053 | 0.056 | 0.055 | 0.053 | 0.056 | 0.058 | 0.065 | 0.064 | 0.072 | 0.077 |
| s_ep      | 0.019 | 0.017 | 0.015 | 0.017 | 0.018 | 0.015 | 0.014 | 0.018 | 0.018 | 0.029 |
| sp_ei     | 0.105 | 0.107 | 0.104 | 0.115 | 0.115 | 0.118 | 0.133 | 0.128 | 0.138 | 0.160 |
| ratio     | 0.183 | 0.158 | 0.140 | 0.148 | 0.156 | 0.128 | 0.106 | 0.144 | 0.134 | 0.182 |

# Table 2: continue..

<center>

Portfolios For Estimation 2006-10

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.362 | 0.291 | 0.482 | 0.602 | 0.817 | 0.853 | 0.907 | 0.930 | 0.907 | 0.912 |
| s_beta    | 0.041 | 0.051 | 0.034 | 0.033 | 0.036 | 0.031 | 0.037 | 0.030 | 0.022 | 0.025 |
| Rsquared  | 0.579 | 0.364 | 0.780 | 0.849 | 0.898 | 0.928 | 0.911 | 0.944 | 0.967 | 0.958 |
| s_Rp      | 0.032 | 0.032 | 0.036 | 0.044 | 0.057 | 0.059 | 0.063 | 0.064 | 0.061 | 0.062 |
| s_ep      | 0.021 | 0.026 | 0.017 | 0.017 | 0.018 | 0.016 | 0.019 | 0.015 | 0.011 | 0.013 |
| sp_ei     | 0.054 | 0.047 | 0.057 | 0.066 | 0.079 | 0.083 | 0.086 | 0.093 | 0.089 | 0.085 |
| ratio     | 0.384 | 0.549 | 0.298 | 0.256 | 0.232 | 0.191 | 0.219 | 0.163 | 0.125 | 0.149 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.035 | 0.984 | 1.180 | 1.147 | 1.345 | 1.131 | 1.264 | 1.297 | 1.419 | 1.396 |
| s_beta    | 0.030 | 0.032 | 0.037 | 0.035 | 0.040 | 0.034 | 0.038 | 0.033 | 0.037 | 0.046 |
| Rsquared  | 0.954 | 0.941 | 0.945 | 0.948 | 0.952 | 0.950 | 0.951 | 0.963 | 0.962 | 0.941 |
| s_Rp      | 0.071 | 0.068 | 0.081 | 0.078 | 0.092 | 0.077 | 0.086 | 0.088 | 0.096 | 0.096 |
| s_ep      | 0.015 | 0.016 | 0.019 | 0.018 | 0.020 | 0.017 | 0.019 | 0.017 | 0.019 | 0.023 |
| sp_ei     | 0.107 | 0.094 | 0.102 | 0.102 | 0.109 | 0.107 | 0.108 | 0.113 | 0.110 | 0.124 |
| ratio     | 0.141 | 0.176 | 0.185 | 0.175 | 0.185 | 0.161 | 0.177 | 0.149 | 0.170 | 0.188 |

# Table 2: continue..

<center>

Portfolios For Estimation 2014-18

<center>

| statistic | 1     | 2     | 3     | 4     | 5     | 6     | 7     | 8     | 9     | 10    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 0.134 | 0.192 | 0.444 | 0.638 | 0.682 | 0.740 | 0.802 | 0.825 | 0.775 | 0.880 |
| s_beta    | 0.062 | 0.072 | 0.055 | 0.059 | 0.040 | 0.037 | 0.038 | 0.033 | 0.037 | 0.033 |
| Rsquared  | 0.074 | 0.108 | 0.529 | 0.665 | 0.835 | 0.874 | 0.887 | 0.914 | 0.886 | 0.926 |
| s_Rp      | 0.018 | 0.021 | 0.022 | 0.028 | 0.027 | 0.028 | 0.030 | 0.031 | 0.029 | 0.033 |
| s_ep      | 0.017 | 0.020 | 0.015 | 0.016 | 0.011 | 0.010 | 0.010 | 0.009 | 0.010 | 0.009 |
| sp_ei     | 0.030 | 0.041 | 0.050 | 0.060 | 0.059 | 0.063 | 0.062 | 0.063 | 0.060 | 0.070 |
| ratio     | 0.558 | 0.483 | 0.298 | 0.268 | 0.183 | 0.159 | 0.165 | 0.143 | 0.165 | 0.127 |

| statistic | 11    | 12    | 13    | 14    | 15    | 16    | 17    | 18    | 19    | 20    |
|-----------|-------|-------|-------|-------|-------|-------|-------|-------|-------|-------|
| beta      | 1.085 | 1.089 | 1.128 | 1.042 | 1.160 | 1.330 | 1.228 | 1.411 | 1.419 | 1.508 |
| s_beta    | 0.034 | 0.039 | 0.036 | 0.038 | 0.041 | 0.050 | 0.046 | 0.043 | 0.057 | 0.066 |
| Rsquared  | 0.946 | 0.929 | 0.943 | 0.928 | 0.932 | 0.925 | 0.923 | 0.949 | 0.914 | 0.900 |
| s_Rp      | 0.040 | 0.040 | 0.041 | 0.039 | 0.043 | 0.049 | 0.046 | 0.052 | 0.053 | 0.057 |
| s_ep      | 0.009 | 0.011 | 0.010 | 0.010 | 0.011 | 0.013 | 0.013 | 0.012 | 0.016 | 0.018 |
| sp_ei     | 0.068 | 0.065 | 0.071 | 0.063 | 0.083 | 0.085 | 0.083 | 0.084 | 0.092 | 0.100 |
| ratio     | 0.135 | 0.164 | 0.140 | 0.164 | 0.134 | 0.159 | 0.152 | 0.139 | 0.169 | 0.180 |

# Table 3 Panel(A): Summary Results For the Regression

| Period    | ${\bar{\hat{\gamma_0}}}$ | ${\bar{\hat{\gamma_1}}}$ | ${\bar{\hat{\gamma_2}}}$ | ${\bar{\hat{\gamma_3}}}$ | ${\bar{\hat{\gamma_0-_{R_f}}}}$ | $s({\hat{\gamma_0}})$ | $s({\hat{\gamma_1}})$ | $s({\hat{\gamma_2}})$ | $s({\hat{\gamma_3}})$ | ${\rho _0}({\hat{\gamma_0-{R_f}}})$ |
|--------------|------------|------------|----------|----------|----------|---------|-----------|-------|-------|----------|
| Panel A:  |                          |                          |                          |                          |                                 |                       |                       |                       |                       |                                     |
| 1935-2022 | 0.0069                   | 0.0057                   | ...                      | ...                      | 0.0042                          | 0.0341                | 0.0607                | ...                   | ...                   | 0.0936                              |
| 1935-1945 | 0.0005                   | 0.0187                   | ...                      | ...                      | 0.0003                          | 0.0506                | 0.1004                | ...                   | ...                   | 0.0489                              |
| 1946-1955 | 0.0090                   | 0.0025                   | ...                      | ...                      | 0.0080                          | 0.0255                | 0.0411                | ...                   | ...                   | 0.1047                              |
| 1956-1965 | 0.0070                   | 0.0046                   | ...                      | ...                      | 0.0047                          | 0.0290                | 0.0411                | ...                   | ...                   | 0.3579                              |
| 1966-1975 | 0.0049                   | 0.0018                   | ...                      | ...                      | 0.0003                          | 0.0382                | 0.0625                | ...                   | ...                   | 0.1233                              |
| 1976-1985 | 0.0092                   | 0.0103                   | ...                      | ...                      | 0.0020                          | 0.0329                | 0.0580                | ...                   | ...                   | 0.1369                              |
| 1986-1995 | 0.0124                   | 0.0000                   | ...                      | ...                      | 0.0079                          | 0.0358                | 0.0539                | ...                   | ...                   | 0.0230                              |
| 1996-2005 | 0.0080                   | 0.0054                   | ...                      | ...                      | 0.0050                          | 0.0305                | 0.0489                | ...                   | ...                   | -0.0559                             |
| 2006-2015 | 0.0068                   | 0.0014                   | ...                      | ...                      | 0.0059                          | 0.0266                | 0.0577                | ...                   | ...                   | 0.0667                              |
| 2016-2022 | 0.0047                   | 0.0055                   | ...                      | ...                      | 0.0038                          | 0.0253                | 0.0537                | ...                   | ...                   | -0.0185                             |
| 1935-1940 | -0.0048                  | 0.0170                   | ...                      | ...                      | -0.0048                         | 0.0619                | 0.1226                | ...                   | ...                   | -0.0097                             |
| 1941-1945 | 0.0068                   | 0.0208                   | ...                      | ...                      | 0.0065                          | 0.0314                | 0.0655                | ...                   | ...                   | 0.2519                              |
| 1946-1950 | 0.0051                   | 0.0030                   | ...                      | ...                      | 0.0045                          | 0.0302                | 0.0471                | ...                   | ...                   | 0.1667                              |
| 1951-1955 | 0.0128                   | 0.0021                   | ...                      | ...                      | 0.0116                          | 0.0193                | 0.0344                | ...                   | ...                   | -0.0419                             |
| 1956-1960 | 0.0152                   | -0.0061                  | ...                      | ...                      | 0.0130                          | 0.0207                | 0.0347                | ...                   | ...                   | 0.1387                              |
| 1961-1965 | -0.0012                  | 0.0152                   | ...                      | ...                      | -0.0037                         | 0.0337                | 0.0445                | ...                   | ...                   | 0.3557                              |
| 1966-1970 | 0.0084                   | -0.0019                  | ...                      | ...                      | 0.0040                          | 0.0390                | 0.0560                | ...                   | ...                   | 0.1394                              |
| 1971-1975 | 0.0014                   | 0.0055                   | ...                      | ...                      | -0.0033                         | 0.0375                | 0.0686                | ...                   | ...                   | 0.1069                              |
| 1976-1980 | 0.0013                   | 0.0207                   | ...                      | ...                      | -0.0050                         | 0.0309                | 0.0635                | ...                   | ...                   | 0.1642                              |
| 1981-1985 | 0.0172                   | -0.0001                  | ...                      | ...                      | 0.0090                          | 0.0331                | 0.0504                | ...                   | ...                   | 0.0390                              |
| 1986-1990 | 0.0183                   | -0.0106                  | ...                      | ...                      | 0.0128                          | 0.0365                | 0.0530                | ...                   | ...                   | -0.0972                             |
| 1991-1995 | 0.0065                   | 0.0106                   | ...                      | ...                      | 0.0030                          | 0.0344                | 0.0530                | ...                   | ...                   | 0.1300                              |
| 1996-2000 | 0.0109                   | 0.0021                   | ...                      | ...                      | 0.0067                          | 0.0329                | 0.0474                | ...                   | ...                   | 0.0191                              |
| 2001-2005 | 0.0052                   | 0.0088                   | ...                      | ...                      | 0.0034                          | 0.0278                | 0.0505                | ...                   | ...                   | -0.0506                             |
| 2006-2010 | 0.0036                   | 0.0057                   | ...                      | ...                      | 0.0017                          | 0.0284                | 0.0652                | ...                   | ...                   | 0.0425                              |
| 2011-2015 | 0.0101                   | -0.0029                  | ...                      | ...                      | 0.0101                          | 0.0245                | 0.0492                | ...                   | ...                   | 0.0318                              |
| 2016-2022 | 0.0047                   | 0.0055                   | ...                      | ...                      | 0.0038                          | 0.0253                | 0.0537                | ...                   | ...                   | -0.0185                             |

# Table 3 Panel(A):Continue...

| Period    | ${\rho _M}({\hat{\gamma_1}})$ | ${\rho _0}({\hat{\gamma_2}})$ | ${\rho _0}({\hat{\gamma_3}})$ | ${t}({\bar{\hat{\gamma_0}}})$ | ${t}({\bar{\hat{\gamma_1}}})$ | ${t}({\bar{\hat{\gamma_2}}})$ | ${t}({\bar{\hat{\gamma_3}}})$ | ${t}({\bar{\hat{\gamma_0-_{R_f}}}})$ | $\bar{{{r^2}}}$ | $s({{r^2}})$ |
|---------------|------------|--------|-------|---------------|-------------|-------|------|-------------|-------------|------------|
| Panel A:  |                               |                               |                               |                               |                               |                               |                               |                                      |                 |              |
| 1935-2022 | 0.0936                        | ...                           | ...                           | 6.6191                        | 3.0726                        | ...                           | ...                           | 4.0081                               | 0.3365          | 0.3045       |
| 1935-1945 | -0.0437                       | ...                           | ...                           | 0.1069                        | 2.1424                        | ...                           | ...                           | 0.0744                               | 0.2739          | 0.2892       |
| 1946-1955 | 0.0728                        | ...                           | ...                           | 3.8435                        | 0.6754                        | ...                           | ...                           | 3.4414                               | 0.3185          | 0.3168       |
| 1956-1965 | 0.1978                        | ...                           | ...                           | 2.6377                        | 1.2131                        | ...                           | ...                           | 1.7495                               | 0.2675          | 0.2857       |
| 1966-1975 | 0.1021                        | ...                           | ...                           | 1.4024                        | 0.3174                        | ...                           | ...                           | 0.0953                               | 0.3082          | 0.2824       |
| 1976-1985 | 0.2272                        | ...                           | ...                           | 3.0809                        | 1.9369                        | ...                           | ...                           | 0.6783                               | 0.3691          | 0.3065       |
| 1986-1995 | 0.3032                        | ...                           | ...                           | 3.7910                        | 0.0066                        | ...                           | ...                           | 2.4286                               | 0.2771          | 0.2656       |
| 1996-2005 | 0.0977                        | ...                           | ...                           | 2.8878                        | 1.2207                        | ...                           | ...                           | 1.8219                               | 0.3749          | 0.2879       |
| 2006-2015 | 0.1619                        | ...                           | ...                           | 2.8156                        | 0.2697                        | ...                           | ...                           | 2.4211                               | 0.4377          | 0.3205       |
| 2016-2022 | -0.0718                       | ...                           | ...                           | 1.6867                        | 0.9390                        | ...                           | ...                           | 1.3945                               | 0.4382          | 0.3473       |
| 1935-1940 | -0.0925                       | ...                           | ...                           | -0.6532                       | 1.1749                        | ...                           | ...                           | -0.6637                              | 0.2144          | 0.2840       |
| 1941-1945 | 0.1549                        | ...                           | ...                           | 1.6653                        | 2.4626                        | ...                           | ...                           | 1.6130                               | 0.3454          | 0.2812       |
| 1946-1950 | 0.0294                        | ...                           | ...                           | 1.3167                        | 0.4918                        | ...                           | ...                           | 1.1465                               | 0.4025          | 0.3240       |
| 1951-1955 | 0.1043                        | ...                           | ...                           | 5.1291                        | 0.4671                        | ...                           | ...                           | 4.6235                               | 0.2345          | 0.2883       |
| 1956-1960 | 0.1640                        | ...                           | ...                           | 5.6729                        | -1.3651                       | ...                           | ...                           | 4.8654                               | 0.2141          | 0.3037       |
| 1961-1965 | 0.1472                        | ...                           | ...                           | -0.2714                       | 2.6521                        | ...                           | ...                           | -0.8481                              | 0.3210          | 0.2580       |
| 1966-1970 | 0.1430                        | ...                           | ...                           | 1.6725                        | -0.2595                       | ...                           | ...                           | 0.7937                               | 0.3107          | 0.2805       |
| 1971-1975 | 0.0609                        | ...                           | ...                           | 0.2850                        | 0.6204                        | ...                           | ...                           | -0.6814                              | 0.3056          | 0.2868       |
| 1976-1980 | 0.1910                        | ...                           | ...                           | 0.3292                        | 2.5178                        | ...                           | ...                           | -1.2664                              | 0.3675          | 0.2954       |
| 1981-1985 | 0.2233                        | ...                           | ...                           | 4.0150                        | -0.0204                       | ...                           | ...                           | 2.0819                               | 0.3708          | 0.3197       |
| 1986-1990 | 0.3122                        | ...                           | ...                           | 3.8865                        | -1.5448                       | ...                           | ...                           | 2.7228                               | 0.2762          | 0.2817       |
| 1991-1995 | 0.2411                        | ...                           | ...                           | 1.4587                        | 1.5554                        | ...                           | ...                           | 0.6716                               | 0.2781          | 0.2508       |
| 1996-2000 | 0.1079                        | ...                           | ...                           | 2.5619                        | 0.3441                        | ...                           | ...                           | 1.5796                               | 0.3495          | 0.2667       |
| 2001-2005 | 0.0713                        | ...                           | ...                           | 1.4425                        | 1.3485                        | ...                           | ...                           | 0.9477                               | 0.4004          | 0.3078       |
| 2006-2010 | 0.2567                        | ...                           | ...                           | 0.9790                        | 0.6783                        | ...                           | ...                           | 0.4762                               | 0.4523          | 0.3028       |
| 2011-2015 | -0.0210                       | ...                           | ...                           | 3.1891                        | -0.4512                       | ...                           | ...                           | 3.1829                               | 0.4230          | 0.3391       |
| 2016-2022 | -0.0718                       | ...                           | ...                           | 1.6867                        | 0.9390                        | ...                           | ...                           | 1.3945                               | 0.4382          | 0.3473       |

# Table 3 Panel(B):Summary Results for the Regression

| Period    | ${\bar{\hat{\gamma_0}}}$ | ${\bar{\hat{\gamma_1}}}$ | ${\bar{\hat{\gamma_2}}}$ | ${\bar{\hat{\gamma_3}}}$ | ${\bar{\hat{\gamma_0-_{R_f}}}}$ | $s({\hat{\gamma_0}})$ | $s({\hat{\gamma_1}})$ | $s({\hat{\gamma_2}})$ | $s({\hat{\gamma_3}})$ | ${\rho _0}({\hat{\gamma_0-{R_f}}})$ |
|---------------------|--------------|-------------|--------------|--------|--------------|---------------|--------------|-------------|-------|---------------|
| Panel B:  |                          |                          |                          |                          |                                 |                       |                       |                       |                       |                                     |
| 1935-2022 | 0.0057                   | 0.0093                   | -0.0071                  | ...                      | 0.0057                          | 0.0352                | 0.0925                | 0.0354                | ...                   | 0.0592                              |
| 1935-1945 | 0.0020                   | 0.0155                   | 0.0016                   | ...                      | 0.0018                          | 0.1160                | 0.2484                | 0.1280                | ...                   | -0.0219                             |
| 1946-1955 | -0.0007                  | 0.0229                   | -0.0098                  | ...                      | -0.0017                         | 0.0339                | 0.0949                | 0.0376                | ...                   | 0.0180                              |
| 1956-1965 | 0.0052                   | 0.0084                   | -0.0019                  | ...                      | 0.0028                          | 0.0591                | 0.1181                | 0.0592                | ...                   | 0.3042                              |
| 1966-1975 | 0.0030                   | 0.0060                   | -0.0022                  | ...                      | -0.0016                         | 0.0881                | 0.1819                | 0.0927                | ...                   | 0.0114                              |
| 1976-1985 | 0.0061                   | 0.0166                   | -0.0029                  | ...                      | -0.0012                         | 0.0797                | 0.1857                | 0.0743                | ...                   | 0.2078                              |
| 1986-1995 | 0.0123                   | -0.0014                  | 0.0015                   | ...                      | 0.0078                          | 0.0558                | 0.1402                | 0.0760                | ...                   | 0.0661                              |
| 1996-2005 | 0.0116                   | -0.0042                  | 0.0056                   | ...                      | 0.0087                          | 0.0405                | 0.1020                | 0.0550                | ...                   | 0.0152                              |
| 2006-2015 | 0.0058                   | 0.0047                   | -0.0021                  | ...                      | 0.0049                          | 0.0461                | 0.1315                | 0.0521                | ...                   | 0.1148                              |
| 2016-2022 | 0.0013                   | 0.0146                   | -0.0049                  | ...                      | 0.0005                          | 0.0277                | 0.0615                | 0.0233                | ...                   | 0.0637                              |
| 1935-1940 | -0.0093                  | 0.0278                   | -0.0055                  | ...                      | -0.0094                         | 0.1429                | 0.3188                | 0.1578                | ...                   | -0.0429                             |
| 1941-1945 | 0.0155                   | 0.0009                   | 0.0100                   | ...                      | 0.0152                          | 0.0705                | 0.1195                | 0.0794                | ...                   | 0.0284                              |
| 1946-1950 | -0.0011                  | 0.0160                   | -0.0061                  | ...                      | -0.0018                         | 0.0356                | 0.0998                | 0.0369                | ...                   | 0.1244                              |
| 1951-1955 | -0.0004                  | 0.0298                   | -0.0136                  | ...                      | -0.0016                         | 0.0324                | 0.0899                | 0.0381                | ...                   | -0.1310                             |
| 1956-1960 | 0.0113                   | 0.0022                   | -0.0041                  | ...                      | 0.0092                          | 0.0381                | 0.0898                | 0.0435                | ...                   | 0.2182                              |
| 1961-1965 | -0.0010                  | 0.0146                   | 0.0004                   | ...                      | -0.0035                         | 0.0743                | 0.1414                | 0.0719                | ...                   | 0.3092                              |
| 1966-1970 | 0.0016                   | 0.0133                   | -0.0079                  | ...                      | -0.0029                         | 0.0764                | 0.1671                | 0.0696                | ...                   | 0.0254                              |
| 1971-1975 | 0.0044                   | -0.0014                  | 0.0035                   | ...                      | -0.0002                         | 0.0990                | 0.1967                | 0.1114                | ...                   | 0.0060                              |
| 1976-1980 | -0.0017                  | 0.0263                   | -0.0025                  | ...                      | -0.0079                         | 0.0905                | 0.2170                | 0.0891                | ...                   | 0.2358                              |
| 1981-1985 | 0.0138                   | 0.0068                   | -0.0033                  | ...                      | 0.0056                          | 0.0672                | 0.1494                | 0.0565                | ...                   | 0.1516                              |
| 1986-1990 | 0.0089                   | 0.0106                   | -0.0111                  | ...                      | 0.0034                          | 0.0635                | 0.1592                | 0.0694                | ...                   | -0.0502                             |
| 1991-1995 | 0.0156                   | -0.0134                  | 0.0141                   | ...                      | 0.0121                          | 0.0471                | 0.1184                | 0.0806                | ...                   | 0.2538                              |
| 1996-2000 | 0.0143                   | -0.0070                  | 0.0054                   | ...                      | 0.0101                          | 0.0429                | 0.1121                | 0.0589                | ...                   | 0.0884                              |
| 2001-2005 | 0.0090                   | -0.0015                  | 0.0059                   | ...                      | 0.0073                          | 0.0382                | 0.0917                | 0.0513                | ...                   | -0.0766                             |
| 2006-2010 | 0.0060                   | 0.0001                   | 0.0029                   | ...                      | 0.0041                          | 0.0552                | 0.1622                | 0.0646                | ...                   | 0.1176                              |
| 2011-2015 | 0.0057                   | 0.0093                   | -0.0071                  | ...                      | 0.0057                          | 0.0352                | 0.0925                | 0.0354                | ...                   | 0.0592                              |
| 2016-2022 | 0.0013                   | 0.0146                   | -0.0049                  | ...                      | 0.0005                          | 0.0277                | 0.0615                | 0.0233                | ...                   | 0.0637                              |

# Table 3 Panel(B):Continue...

| ${\rho _M}({\hat{\gamma_1}})$ | ${\rho _0}({\hat{\gamma_2}})$ | ${\rho _0}({\hat{\gamma_3}})$ | ${t}({\bar{\hat{\gamma_0}}})$ | ${t}({\bar{\hat{\gamma_1}}})$ | ${t}({\bar{\hat{\gamma_2}}})$ | ${t}({\bar{\hat{\gamma_3}}})$ | ${t}({\bar{\hat{\gamma_0-_{R_f}}}})$ | $\bar{{{r^2}}}$ | $s({{r^2}})$ |
|--------------|--------|--------|--------|--------|--------|--------|---------|--------|--------|
| Panel B:                      |                               |                               |                               |                               |                               |                               |                                      |                 |              |
| 1935-2022                     | -0.0265                       | 0.0857                        | ...                           | 1.2579                        | 0.7782                        | -1.5536                       | ...                                  | 1.2540          | 0.4885       |
| 1935-1945                     | -0.0624                       | -0.0675                       | ...                           | 0.1937                        | 0.7193                        | 0.1394                        | ...                                  | 0.1795          | 0.2838       |
| 1946-1955                     | 0.0140                        | -0.0476                       | ...                           | -0.2419                       | 2.6472                        | -2.8640                       | ...                                  | -0.5469         | 0.3464       |
| 1956-1965                     | 0.2402                        | 0.1610                        | ...                           | 0.9569                        | 0.7798                        | -0.3440                       | ...                                  | 0.5258          | 0.3123       |
| 1966-1975                     | -0.0260                       | -0.1131                       | ...                           | 0.3743                        | 0.3589                        | -0.2562                       | ...                                  | -0.1930         | 0.3437       |
| 1976-1985                     | 0.2305                        | 0.1666                        | ...                           | 0.8330                        | 0.9770                        | -0.4254                       | ...                                  | -0.1616         | 0.4277       |
| 1986-1995                     | 0.0393                        | 0.0043                        | ...                           | 2.4103                        | -0.1093                       | 0.2171                        | ...                                  | 1.5260          | 0.3362       |
| 1996-2005                     | 0.0113                        | -0.0734                       | ...                           | 3.1455                        | -0.4527                       | 1.1252                        | ...                                  | 2.3441          | 0.4412       |
| 2006-2015                     | 0.0874                        | 0.1319                        | ...                           | 1.3891                        | 0.3914                        | -0.4415                       | ...                                  | 1.1660          | 0.5077       |
| 2016-2022                     | -0.1019                       | -0.1276                       | ...                           | 0.4418                        | 2.1700                        | -1.9491                       | ...                                  | 0.1732          | 0.4759       |
| 1935-1940                     | -0.0625                       | -0.0950                       | ...                           | -0.5527                       | 0.7391                        | -0.2966                       | ...                                  | -0.5572         | 0.2118       |
| 1941-1945                     | -0.0696                       | 0.0584                        | ...                           | 1.6988                        | 0.0575                        | 0.9785                        | ...                                  | 1.6757          | 0.3701       |
| 1946-1950                     | 0.1028                        | 0.0373                        | ...                           | -0.2390                       | 1.2441                        | -1.2751                       | ...                                  | -0.3834         | 0.4259       |
| 1951-1955                     | -0.1391                       | -0.1339                       | ...                           | -0.0953                       | 2.5678                        | -2.7544                       | ...                                  | -0.3878         | 0.2669       |
| 1956-1960                     | 0.0950                        | 0.1649                        | ...                           | 2.3008                        | 0.1877                        | -0.7293                       | ...                                  | 1.8688          | 0.2652       |
| 1961-1965                     | 0.2958                        | 0.1578                        | ...                           | -0.1028                       | 0.8019                        | 0.0405                        | ...                                  | -0.3656         | 0.3595       |
| 1966-1970                     | 0.0512                        | -0.0585                       | ...                           | 0.1593                        | 0.6180                        | -0.8757                       | ...                                  | -0.2901         | 0.3282       |
| 1971-1975                     | -0.0603                       | -0.1108                       | ...                           | 0.3480                        | -0.0557                       | 0.2456                        | ...                                  | -0.0192         | 0.3591       |
| 1976-1980                     | 0.2253                        | 0.1579                        | ...                           | -0.1421                       | 0.9406                        | -0.2134                       | ...                                  | -0.6815         | 0.4496       |
| 1981-1985                     | 0.2443                        | 0.1976                        | ...                           | 1.5899                        | 0.3518                        | -0.4542                       | ...                                  | 0.6464          | 0.4058       |
| 1986-1990                     | 0.0195                        | -0.1500                       | ...                           | 1.0874                        | 0.5176                        | -1.2420                       | ...                                  | 0.4148          | 0.3332       |
| 1991-1995                     | 0.0513                        | 0.0814                        | ...                           | 2.5708                        | -0.8787                       | 1.3583                        | ...                                  | 2.0004          | 0.3392       |
| 1996-2000                     | 0.1350                        | 0.0815                        | ...                           | 2.5770                        | -0.4822                       | 0.7114                        | ...                                  | 1.8188          | 0.4089       |
| 2001-2005                     | -0.1242                       | -0.1684                       | ...                           | 1.8263                        | -0.1229                       | 0.8892                        | ...                                  | 1.4698          | 0.4735       |
| 2006-2010                     | 0.1103                        | 0.1200                        | ...                           | 0.8385                        | 0.0052                        | 0.3474                        | ...                                  | 0.5785          | 0.5269       |
| 2011-2015                     | -0.0265                       | 0.0857                        | ...                           | 1.2579                        | 0.7782                        | -1.5536                       | ...                                  | 1.2540          | 0.4885       |
| 2016-2022                     | -0.1019                       | -0.1276                       | ...                           | 0.4418                        | 2.1700                        | -1.9491                       | ...                                  | 0.1732          | 0.4759       |

# Table 3 Panel(C):Summary Results for the Regression

| Period    | ${\bar{\hat{\gamma_0}}}$ | ${\bar{\hat{\gamma_1}}}$ | ${\bar{\hat{\gamma_2}}}$ | ${\bar{\hat{\gamma_3}}}$ | ${\bar{\hat{\gamma_0-_{R_f}}}}$ | $s({\hat{\gamma_0}})$ | $s({\hat{\gamma_1}})$ | $s({\hat{\gamma_2}})$ | $s({\hat{\gamma_3}})$ | ${\rho _0}({\hat{\gamma_0-{R_f}}})$ |
|----------------------|-----------------|-----------------|-------|--------------------|-----------------|------------------|------------------|-------|---------------|-----------------|
| Panel C:  |                          |                          |                          |                          |                                 |                       |                       |                       |                       |                                     |
| 1935-2022 | 0.0064                   | 0.0042                   | ...                      | 0.0191                   | 0.0037                          | 0.0434                | 0.0791                | ...                   | 0.9465                | 0.0988                              |
| 1935-1945 | -0.0011                  | 0.0171                   | ...                      | 0.0427                   | -0.0012                         | 0.0540                | 0.1302                | ...                   | 0.8927                | 0.0745                              |
| 1946-1955 | 0.0108                   | 0.0066                   | ...                      | -0.0861                  | 0.0099                          | 0.0380                | 0.0582                | ...                   | 0.8586                | -0.0164                             |
| 1956-1965 | 0.0075                   | 0.0058                   | ...                      | -0.0253                  | 0.0052                          | 0.0370                | 0.0538                | ...                   | 1.0046                | 0.3004                              |
| 1966-1975 | 0.0051                   | 0.0018                   | ...                      | -0.0099                  | 0.0006                          | 0.0484                | 0.0758                | ...                   | 1.1315                | 0.0564                              |
| 1976-1985 | 0.0051                   | 0.0001                   | ...                      | 0.1569                   | -0.0021                         | 0.0496                | 0.0845                | ...                   | 1.3616                | 0.3109                              |
| 1986-1995 | 0.0139                   | 0.0006                   | ...                      | -0.0262                  | 0.0094                          | 0.0441                | 0.0695                | ...                   | 0.8287                | -0.0196                             |
| 1996-2005 | 0.0050                   | -0.0015                  | ...                      | 0.1110                   | 0.0020                          | 0.0407                | 0.0663                | ...                   | 0.7964                | -0.0609                             |
| 2006-2015 | 0.0060                   | 0.0001                   | ...                      | 0.0311                   | 0.0050                          | 0.0381                | 0.0750                | ...                   | 0.7594                | 0.0313                              |
| 2016-2022 | 0.0060                   | 0.0069                   | ...                      | -0.0438                  | 0.0052                          | 0.0306                | 0.0607                | ...                   | 0.5871                | -0.0621                             |
| 1935-1940 | -0.0040                  | 0.0232                   | ...                      | -0.0524                  | -0.0041                         | 0.0607                | 0.1694                | ...                   | 0.8718                | -0.0141                             |
| 1941-1945 | 0.0025                   | 0.0098                   | ...                      | 0.1568                   | 0.0023                          | 0.0449                | 0.0548                | ...                   | 0.9113                | 0.2555                              |
| 1946-1950 | 0.0070                   | 0.0077                   | ...                      | -0.0836                  | 0.0063                          | 0.0454                | 0.0713                | ...                   | 0.9687                | 0.0291                              |
| 1951-1955 | 0.0146                   | 0.0055                   | ...                      | -0.0886                  | 0.0134                          | 0.0285                | 0.0419                | ...                   | 0.7405                | -0.0714                             |
| 1956-1960 | 0.0119                   | -0.0092                  | ...                      | 0.1064                   | 0.0098                          | 0.0359                | 0.0482                | ...                   | 1.0719                | 0.2685                              |
| 1961-1965 | 0.0032                   | 0.0209                   | ...                      | -0.1570                  | 0.0007                          | 0.0379                | 0.0552                | ...                   | 0.9227                | 0.3037                              |
| 1966-1970 | 0.0113                   | 0.0021                   | ...                      | -0.0987                  | 0.0069                          | 0.0445                | 0.0689                | ...                   | 0.9965                | 0.0058                              |
| 1971-1975 | -0.0011                  | 0.0015                   | ...                      | 0.0788                   | -0.0058                         | 0.0517                | 0.0827                | ...                   | 1.2543                | 0.1161                              |
| 1976-1980 | -0.0112                  | -0.0087                  | ...                      | 0.4651                   | -0.0175                         | 0.0526                | 0.0740                | ...                   | 1.4394                | 0.3518                              |
| 1981-1985 | 0.0215                   | 0.0089                   | ...                      | -0.1513                  | 0.0133                          | 0.0406                | 0.0936                | ...                   | 1.2141                | 0.0643                              |
| 1986-1990 | 0.0223                   | -0.0015                  | ...                      | -0.1551                  | 0.0167                          | 0.0474                | 0.0879                | ...                   | 0.9847                | -0.1471                             |
| 1991-1995 | 0.0055                   | 0.0026                   | ...                      | 0.1027                   | 0.0020                          | 0.0391                | 0.0447                | ...                   | 0.6178                | 0.1122                              |
| 1996-2000 | 0.0076                   | -0.0058                  | ...                      | 0.1327                   | 0.0033                          | 0.0473                | 0.0674                | ...                   | 0.9159                | 0.0011                              |
| 2001-2005 | 0.0024                   | 0.0028                   | ...                      | 0.0893                   | 0.0006                          | 0.0330                | 0.0655                | ...                   | 0.6627                | -0.0033                             |
| 2006-2010 | 0.0013                   | 0.0018                   | ...                      | 0.0809                   | -0.0005                         | 0.0402                | 0.0917                | ...                   | 0.8749                | -0.0697                             |
| 2011-2015 | 0.0106                   | -0.0016                  | ...                      | -0.0187                  | 0.0106                          | 0.0356                | 0.0540                | ...                   | 0.6267                | 0.1096                              |
| 2016-2022 | 0.0060                   | 0.0069                   | ...                      | -0.0438                  | 0.0052                          | 0.0306                | 0.0607                | ...                   | 0.5871                | -0.0621                             |

# Table 3 Panel(C):Continue...

| Period    | ${\rho _M}({\hat{\gamma_1}})$ | ${\rho _0}({\hat{\gamma_2}})$ | ${\rho _0}({\hat{\gamma_3}})$ | ${t}({\bar{\hat{\gamma_0}}})$ | ${t}({\bar{\hat{\gamma_1}}})$ | ${t}({\bar{\hat{\gamma_2}}})$ | ${t}({\bar{\hat{\gamma_3}}})$ | ${t}({\bar{\hat{\gamma_0-_{R_f}}}})$ | $\bar{{{r^2}}}$ | $s({{r^2}})$ |
|--------------------------|-------------------|-------|--------------------|--------------------|-------------------|-------|------------------|-----------------|-----------------|--------------|
| Panel C:  |                               |                               |                               |                               |                               |                               |                               |                                      |                 |              |
| 1935-2022 | 0.0238                        | ...                           | 0.0348                        | 4.8080                        | 1.7386                        | ...                           | 0.6542                        | 2.7508                               | 0.3620          | 0.3045       |
| 1935-1945 | -0.0846                       | ...                           | -0.0116                       | -0.2272                       | 1.5126                        | ...                           | 0.5492                        | -0.2577                              | 0.2991          | 0.2927       |
| 1946-1955 | -0.0431                       | ...                           | -0.1494                       | 3.1169                        | 1.2467                        | ...                           | -1.0985                       | 2.8460                               | 0.3545          | 0.3180       |
| 1956-1965 | 0.1735                        | ...                           | 0.1745                        | 2.2299                        | 1.1882                        | ...                           | -0.2755                       | 1.5359                               | 0.2951          | 0.2887       |
| 1966-1975 | 0.0655                        | ...                           | -0.0018                       | 1.1618                        | 0.2655                        | ...                           | -0.0963                       | 0.1301                               | 0.3309          | 0.2935       |
| 1976-1985 | 0.1506                        | ...                           | 0.1396                        | 1.1355                        | 0.0129                        | ...                           | 1.2623                        | -0.4681                              | 0.3736          | 0.3129       |
| 1986-1995 | 0.0785                        | ...                           | -0.0381                       | 3.4506                        | 0.0911                        | ...                           | -0.3464                       | 2.3403                               | 0.3146          | 0.2697       |
| 1996-2005 | 0.0743                        | ...                           | -0.0692                       | 1.3354                        | -0.2502                       | ...                           | 1.5265                        | 0.5325                               | 0.4271          | 0.2735       |
| 2006-2015 | 0.0383                        | ...                           | -0.0385                       | 1.7181                        | 0.0156                        | ...                           | 0.4484                        | 1.4442                               | 0.4525          | 0.3119       |
| 2016-2022 | -0.1161                       | ...                           | -0.1334                       | 1.8003                        | 1.0445                        | ...                           | -0.6843                       | 1.5609                               | 0.4408          | 0.3494       |
| 1935-1940 | -0.0858                       | ...                           | -0.1780                       | -0.5639                       | 1.1643                        | ...                           | -0.5102                       | -0.5747                              | 0.2387          | 0.2811       |
| 1941-1945 | -0.1073                       | ...                           | 0.1398                        | 0.4305                        | 1.3878                        | ...                           | 1.3326                        | 0.3923                               | 0.3716          | 0.2922       |
| 1946-1950 | -0.0219                       | ...                           | -0.0900                       | 1.1893                        | 0.8414                        | ...                           | -0.6684                       | 1.0760                               | 0.4311          | 0.3181       |
| 1951-1955 | -0.1525                       | ...                           | -0.2042                       | 3.9748                        | 1.0193                        | ...                           | -0.9268                       | 3.6406                               | 0.2779          | 0.3014       |
| 1956-1960 | 0.2052                        | ...                           | 0.2824                        | 2.5632                        | -1.4789                       | ...                           | 0.7692                        | 2.1038                               | 0.2506          | 0.3066       |
| 1961-1965 | 0.0802                        | ...                           | 0.0430                        | 0.6538                        | 2.9285                        | ...                           | -1.3178                       | 0.1362                               | 0.3395          | 0.2648       |
| 1966-1970 | 0.0005                        | ...                           | -0.0951                       | 1.9729                        | 0.2392                        | ...                           | -0.7670                       | 1.2069                               | 0.3365          | 0.2795       |
| 1971-1975 | 0.1084                        | ...                           | 0.0679                        | -0.1603                       | 0.1448                        | ...                           | 0.4864                        | -0.8637                              | 0.3253          | 0.3091       |
| 1976-1980 | 0.1512                        | ...                           | 0.1617                        | -1.6530                       | -0.9142                       | ...                           | 2.5029                        | -2.6093                              | 0.3633          | 0.3089       |
| 1981-1985 | 0.1346                        | ...                           | -0.0157                       | 4.0958                        | 0.7396                        | ...                           | -0.9654                       | 2.5206                               | 0.3839          | 0.3192       |
| 1986-1990 | 0.0685                        | ...                           | -0.1204                       | 3.6428                        | -0.1311                       | ...                           | -1.2199                       | 2.7402                               | 0.3031          | 0.2816       |
| 1991-1995 | 0.0979                        | ...                           | 0.0984                        | 1.0868                        | 0.4577                        | ...                           | 1.2873                        | 0.3929                               | 0.3260          | 0.2592       |
| 1996-2000 | 0.0277                        | ...                           | -0.0799                       | 1.2371                        | -0.6685                       | ...                           | 1.1222                        | 0.5488                               | 0.4133          | 0.2524       |
| 2001-2005 | 0.0936                        | ...                           | 0.0136                        | 0.5555                        | 0.3299                        | ...                           | 1.0432                        | 0.1423                               | 0.4408          | 0.2946       |
| 2006-2010 | 0.0886                        | ...                           | -0.0953                       | 0.2560                        | 0.1512                        | ...                           | 0.7160                        | -0.0987                              | 0.4793          | 0.2784       |
| 2011-2015 | -0.1180                       | ...                           | 0.0550                        | 2.3098                        | -0.2260                       | ...                           | -0.2311                       | 2.3055                               | 0.4258          | 0.3424       |
| 2016-2022 | -0.1161                       | ...                           | -0.1334                       | 1.8003                        | 1.0445                        | ...                           | -0.6843                       | 1.5609                               | 0.4408          | 0.3494       |

# Table 3 Panel(D):Summary Results for the Regression

| Period    | ${\bar{\hat{\gamma_0}}}$ | ${\bar{\hat{\gamma_1}}}$ | ${\bar{\hat{\gamma_2}}}$ | ${\bar{\hat{\gamma_3}}}$ | ${\bar{\hat{\gamma_0-_{R_f}}}}$ | $s({\hat{\gamma_0}})$ | $s({\hat{\gamma_1}})$ | $s({\hat{\gamma_2}})$ | $s({\hat{\gamma_3}})$ | ${\rho _0}({\hat{\gamma_0-{R_f}}})$ |
|--------------------------------|--------------------------------|-------------------------------|--------------------------------|---------------------------|---------------------------|---------------------------|---------------------|-----------------------|------------------------|---------------------------|
| Panel D:  |                          |                          |                          |                          |                                 |                       |                       |                       |                       |                                     |
| 1935-2022 | 0.0024                   | 0.0102                   | -0.0037                  | 0.0488                   | -0.0004                         | 0.0765                | 0.1565                | 0.0744                | 0.9076                | 0.0242                              |
| 1935-1945 | -0.0042                  | 0.0209                   | -0.0031                  | 0.0683                   | -0.0044                         | 0.1202                | 0.2513                | 0.1298                | 0.8726                | -0.1615                             |
| 1946-1955 | -0.0009                  | 0.0221                   | -0.0095                  | 0.0107                   | -0.0018                         | 0.0491                | 0.0948                | 0.0372                | 0.8351                | 0.0554                              |
| 1956-1965 | 0.0035                   | 0.0132                   | -0.0041                  | -0.0062                  | 0.0011                          | 0.0633                | 0.1232                | 0.0587                | 0.9824                | 0.2750                              |
| 1966-1975 | -0.0015                  | 0.0100                   | -0.0056                  | 0.0577                   | -0.0061                         | 0.1104                | 0.1925                | 0.1017                | 1.1981                | 0.0106                              |
| 1976-1985 | 0.0032                   | 0.0051                   | -0.0019                  | 0.1464                   | -0.0040                         | 0.0863                | 0.1880                | 0.0725                | 1.2442                | 0.2624                              |
| 1986-1995 | 0.0099                   | 0.0053                   | -0.0030                  | 0.0037                   | 0.0054                          | 0.0619                | 0.1370                | 0.0658                | 0.7332                | 0.0473                              |
| 1996-2005 | 0.0063                   | -0.0036                  | 0.0016                   | 0.1025                   | 0.0033                          | 0.0469                | 0.1013                | 0.0499                | 0.7146                | 0.0448                              |
| 2006-2015 | 0.0047                   | 0.0054                   | -0.0030                  | 0.0201                   | 0.0037                          | 0.0535                | 0.1368                | 0.0526                | 0.6878                | 0.0741                              |
| 2016-2022 | 0.0005                   | 0.0131                   | -0.0050                  | 0.0277                   | -0.0003                         | 0.0349                | 0.0643                | 0.0238                | 0.6294                | 0.0759                              |
| 1935-1940 | -0.0105                  | 0.0314                   | -0.0064                  | -0.0023                  | -0.0106                         | 0.1501                | 0.3262                | 0.1669                | 0.9325                | -0.1698                             |
| 1941-1945 | 0.0033                   | 0.0083                   | 0.0008                   | 0.1531                   | 0.0031                          | 0.0699                | 0.1089                | 0.0623                | 0.7941                | -0.1102                             |
| 1946-1950 | -0.0024                  | 0.0153                   | -0.0064                  | 0.0424                   | -0.0031                         | 0.0564                | 0.1011                | 0.0371                | 0.9193                | 0.1213                              |
| 1951-1955 | 0.0007                   | 0.0288                   | -0.0127                  | -0.0211                  | -0.0006                         | 0.0410                | 0.0885                | 0.0373                | 0.7481                | -0.0536                             |
| 1956-1960 | 0.0059                   | -0.0004                  | -0.0055                  | 0.1599                   | 0.0038                          | 0.0488                | 0.0905                | 0.0426                | 1.0542                | 0.0680                              |
| 1961-1965 | 0.0010                   | 0.0267                   | -0.0026                  | -0.1723                  | -0.0015                         | 0.0755                | 0.1485                | 0.0717                | 0.8827                | 0.3558                              |
| 1966-1970 | 0.0001                   | 0.0173                   | -0.0096                  | 0.0024                   | -0.0044                         | 0.1091                | 0.1821                | 0.0878                | 1.2603                | -0.0303                             |
| 1971-1975 | -0.0030                  | 0.0026                   | -0.0017                  | 0.1131                   | -0.0077                         | 0.1126                | 0.2035                | 0.1145                | 1.1403                | 0.0466                              |
| 1976-1980 | -0.0108                  | -0.0043                  | -0.0003                  | 0.4157                   | -0.0171                         | 0.0990                | 0.2019                | 0.0860                | 1.2314                | 0.2908                              |
| 1981-1985 | 0.0172                   | 0.0145                   | -0.0035                  | -0.1229                  | 0.0090                          | 0.0693                | 0.1743                | 0.0566                | 1.2076                | 0.1539                              |
| 1986-1990 | 0.0106                   | 0.0147                   | -0.0118                  | -0.0611                  | 0.0051                          | 0.0683                | 0.1633                | 0.0656                | 0.8689                | -0.0274                             |
| 1991-1995 | 0.0092                   | -0.0040                  | 0.0058                   | 0.0684                   | 0.0057                          | 0.0554                | 0.1048                | 0.0654                | 0.5664                | 0.1226                              |
| 1996-2000 | 0.0069                   | -0.0054                  | -0.0004                  | 0.1414                   | 0.0027                          | 0.0540                | 0.1086                | 0.0497                | 0.8478                | 0.0697                              |
| 2001-2005 | 0.0056                   | -0.0019                  | 0.0037                   | 0.0637                   | 0.0039                          | 0.0389                | 0.0944                | 0.0504                | 0.5551                | -0.0025                             |
| 2006-2010 | 0.0023                   | -0.0018                  | 0.0015                   | 0.0914                   | 0.0005                          | 0.0625                | 0.1657                | 0.0651                | 0.7265                | 0.0363                              |
| 2011-2015 | 0.0070                   | 0.0125                   | -0.0074                  | -0.0513                  | 0.0070                          | 0.0430                | 0.1009                | 0.0361                | 0.6449                | 0.1278                              |
| 2016-2022 | 0.0005                   | 0.0131                   | -0.0050                  | 0.0277                   | -0.0003                         | 0.0349                | 0.0643                | 0.0238                | 0.6294                | 0.0759                              |

# Table 3 Panel(D):Continue...

| Period    | ${\rho _M}({\hat{\gamma_1}})$ | ${\rho _0}({\hat{\gamma_2}})$ | ${\rho _0}({\hat{\gamma_3}})$ | ${t}({\bar{\hat{\gamma_0}}})$ | ${t}({\bar{\hat{\gamma_1}}})$ | ${t}({\bar{\hat{\gamma_2}}})$ | ${t}({\bar{\hat{\gamma_3}}})$ | ${t}({\bar{\hat{\gamma_0-_{R_f}}}})$ | $\bar{{{r^2}}}$ | $s({{r^2}})$ |
|------------|---------------------|---------------------|------------------------|----------------------|---------------------|----------------------|----------------------|----------------------|---------------------|-------------------|
| Panel D:  |                               |                               |                               |                               |                               |                               |                               |                                      |                 |              |
| 1935-2022 | 0.0265                        | -0.0689                       | 0.0062                        | 1.0057                        | 2.1113                        | -1.6047                       | 1.7471                        | -0.1636                              | 0.3966          | 0.3100       |
| 1935-1945 | -0.0778                       | -0.2061                       | -0.0780                       | -0.4049                       | 0.9538                        | -0.2750                       | 0.8997                        | -0.4186                              | 0.3057          | 0.3110       |
| 1946-1955 | 0.0127                        | 0.0171                        | -0.0927                       | -0.1949                       | 2.5506                        | -2.8067                       | 0.1398                        | -0.4054                              | 0.3641          | 0.3225       |
| 1956-1965 | 0.1906                        | 0.1128                        | 0.1666                        | 0.5968                        | 1.1712                        | -0.7571                       | -0.0689                       | 0.1953                               | 0.3256          | 0.3001       |
| 1966-1975 | -0.0086                       | -0.0921                       | -0.0083                       | -0.1487                       | 0.5672                        | -0.6051                       | 0.5278                        | -0.6019                              | 0.3715          | 0.2949       |
| 1976-1985 | 0.1803                        | 0.1626                        | 0.0742                        | 0.4060                        | 0.2957                        | -0.2812                       | 1.2886                        | -0.5158                              | 0.4313          | 0.3161       |
| 1986-1995 | 0.0653                        | 0.0159                        | -0.0076                       | 1.7528                        | 0.4277                        | -0.5018                       | 0.0548                        | 0.9556                               | 0.3468          | 0.2725       |
| 1996-2005 | 0.0227                        | -0.0648                       | -0.1000                       | 1.4639                        | -0.3940                       | 0.3590                        | 1.5717                        | 0.7669                               | 0.4626          | 0.2721       |
| 2006-2015 | 0.0539                        | 0.1241                        | -0.0715                       | 0.9560                        | 0.4299                        | -0.6177                       | 0.3194                        | 0.7628                               | 0.5173          | 0.3048       |
| 2016-2022 | -0.1862                       | -0.1005                       | -0.0998                       | 0.1413                        | 1.8712                        | -1.9203                       | 0.4040                        | -0.0724                              | 0.4775          | 0.3386       |
| 1935-1940 | -0.0726                       | -0.2049                       | -0.1833                       | -0.5961                       | 0.8155                        | -0.3245                       | -0.0210                       | -0.6005                              | 0.2349          | 0.3014       |
| 1941-1945 | -0.1333                       | -0.1768                       | 0.0758                        | 0.3692                        | 0.5883                        | 0.1024                        | 1.4933                        | 0.3448                               | 0.3906          | 0.3033       |
| 1946-1950 | 0.0891                        | 0.1336                        | 0.0092                        | -0.3325                       | 1.1733                        | -1.3289                       | 0.3571                        | -0.4232                              | 0.4297          | 0.3324       |
| 1951-1955 | -0.1282                       | -0.1224                       | -0.1883                       | 0.1271                        | 2.5254                        | -2.6353                       | -0.2181                       | -0.1043                              | 0.2986          | 0.3009       |
| 1956-1960 | 0.0365                        | -0.0141                       | 0.2682                        | 0.9311                        | -0.0314                       | -1.0055                       | 1.1753                        | 0.5962                               | 0.2750          | 0.3135       |
| 1961-1965 | 0.2361                        | 0.1565                        | 0.0140                        | 0.1061                        | 1.3935                        | -0.2800                       | -1.5119                       | -0.1532                              | 0.3762          | 0.2795       |
| 1966-1970 | 0.0467                        | -0.0491                       | -0.0591                       | 0.0036                        | 0.7363                        | -0.8438                       | 0.0145                        | -0.3116                              | 0.3709          | 0.2766       |
| 1971-1975 | -0.0370                       | -0.1021                       | 0.0544                        | -0.2097                       | 0.0996                        | -0.1130                       | 0.7682                        | -0.5325                              | 0.3720          | 0.3144       |
| 1976-1980 | 0.1120                        | 0.1285                        | 0.0200                        | -0.8470                       | -0.1660                       | -0.0238                       | 2.6147                        | -1.3434                              | 0.4442          | 0.3126       |
| 1981-1985 | 0.2819                        | 0.2474                        | 0.0321                        | 1.9253                        | 0.6435                        | -0.4734                       | -0.7886                       | 1.0127                               | 0.4183          | 0.3218       |
| 1986-1990 | 0.0493                        | -0.0345                       | -0.0629                       | 1.2054                        | 0.6953                        | -1.3920                       | -0.5445                       | 0.5803                               | 0.3398          | 0.2901       |
| 1991-1995 | 0.0536                        | 0.0033                        | 0.0881                        | 1.2846                        | -0.2928                       | 0.6815                        | 0.9356                        | 0.7944                               | 0.3537          | 0.2560       |
| 1996-2000 | 0.1484                        | 0.1181                        | -0.1657                       | 0.9866                        | -0.3857                       | -0.0616                       | 1.2917                        | 0.3837                               | 0.4389          | 0.2612       |
| 2001-2005 | -0.0968                       | -0.1695                       | 0.0549                        | 1.1248                        | -0.1545                       | 0.5628                        | 0.8886                        | 0.7717                               | 0.4864          | 0.2828       |
| 2006-2010 | 0.0952                        | 0.1202                        | -0.1900                       | 0.2864                        | -0.0837                       | 0.1726                        | 0.9741                        | 0.0581                               | 0.5363          | 0.2834       |
| 2011-2015 | -0.1147                       | 0.0647                        | 0.0417                        | 1.2660                        | 0.9611                        | -1.5849                       | -0.6157                       | 1.2628                               | 0.4982          | 0.3261       |
| 2016-2022 | -0.1862                       | -0.1005                       | -0.0998                       | 0.1413                        | 1.8712                        | -1.9203                       | 0.4040                        | -0.0724                              | 0.4775          | 0.3386       |

Analysis of replication result of Table 3

The above table 3 presents the replication results of the Table 3 in the
original paper. The results are presented into the subgroups. The first
row is the result about the whole sample period. The following 9 rows
are longer periods with 10 years (except the last one from 2016 to
2022). The following 22 rows are five-year periods (except the last one
also from 2016 to 2022). Since each regression results related to 32
periods in total, we present the panel results in separate tables.

When comparing the statistics with the original paper covering the same
period, we could see that the results are quite similar, which is
evidence of the validity of our replication.

If the CAPM model is valid, then we have the following three empirical
implication, according to the Fama and MacBeth (1973).

C1: the relationship between expected return of the stock is linear
relationship with market portfolio return, i.e., ${\gamma_2}$=0

C2: the only risk measure is from beta. No other risk measures, i.e.,
${\gamma_3}$=0

C3: higher risk is related to higher return.

For C1, in general, the results in panel B and panel D do not reject C1.
In Panel B, there are only two periods that have
${t}({\bar{\hat{\gamma_2}}})$ larger than 2. One covers 1951 -- 1955,
same as the paper. The other is 2016 -- 2022. In general, the linear
relationship between the expected returns and ${\beta}$ holds for the
sample period.

For C2, the results in panel C and panel D also could not reject C2. All
${t}({\bar{\hat{\gamma_3}}})$ expected period between 1976 and 1980 are
less than 2. This suggests that the CAPM model works fine in our sample
period: there are no other risk measures, except ${\beta}$, that would
systematically affect the expected returns. The time period of 1976 to
1980 cover the crude oil crisis in US history, and that may be the
reason why the idiosyncratic risks also significant in the regression.

For C3, the results in four panels provide some insights about the
model. If the CAPM is true, then the price of the beta should be
significant and positive. However, in the results table, the number of
significance is roughly half. The good news is that all values are
positive. More importantly, for the whole sample period,
${t}({\bar{\hat{\gamma_1}}})$ are all significant.

To test of the market efficiency theory, we resort to the time behavior
of the ${\gamma_1}$, ${\gamma_2}$, and ${\gamma_3}$. Specifically, we
focus on the ${\rho _M}({\hat{\gamma_1}})$,
${\rho _0}({\hat{\gamma_2}})$, and ${\rho _0}({\hat{\gamma_3}})$. What
we find is that, in most periods, the magnitudes of the autocorrelation
is quite small. Specifically, for the years between 1976 and 1986 and
years between 2006 and 2010 are much higher (between 0.25 to 0.32).

In summary, the CAPM model generally holds for all those years. However,
the Market Efficiency Hypothesis is not always holds.

# Table 4: The Behaviour of the Market

| STATISTIC\* |                |                      |                           |                           |                |                                |                                             |               |                   |                   |
|-------------------|-----------|------------|------------|------------|-----------|-------------|-------------|---------------|-----------|----------|
| Period      | $\bar{_{R_m}}$ | $\bar{_{R_m-{R_f}}}$ | $\bar{\hat{_{\gamma_1}}}$ | $\bar{\hat{_{\gamma_0}}}$ | $\bar{_{R_f}}$ | $\frac{\bar{R_m-R_f}}{s(R_m)}$ | $\frac{\bar{\hat{^{_{\gamma_1}}}}}{s(R_m)}$ | $s({_{R_m}})$ | $s({{\gamma_1}})$ | $s({{\gamma_0}})$ |
| 1935-2022   | 0.0127         | 0.0100               | 0.0057                    | 0.0069                    | 0.0027         | 0.1440                         | 0.0826                                      | 0.0695        | 0.061             | 0.034             |
| 1935-1945   | 0.0196         | 0.0194               | 0.0170                    | -0.0048                   | 0.0001         | 0.2207                         | 0.1926                                      | 0.0881        | 0.1               | 0.051             |
| 1946-1955   | 0.0114         | 0.0105               | 0.0208                    | 0.0068                    | 0.0009         | 0.2422                         | 0.4807                                      | 0.0433        | 0.041             | 0.026             |
| 1956-1965   | 0.0114         | 0.0091               | 0.0030                    | 0.0051                    | 0.0023         | 0.2403                         | 0.0794                                      | 0.0377        | 0.041             | 0.029             |
| 1966-1975   | 0.0068         | 0.0023               | 0.0021                    | 0.0128                    | 0.0046         | 0.0349                         | 0.0318                                      | 0.0651        | 0.062             | 0.038             |
| 1976-1985   | 0.0207         | 0.0135               | -0.0061                   | 0.0152                    | 0.0072         | 0.2593                         | -0.1175                                     | 0.0521        | 0.058             | 0.033             |
| 1986-1995   | 0.0127         | 0.0081               | 0.0152                    | -0.0012                   | 0.0045         | 0.1774                         | 0.3320                                      | 0.0459        | 0.054             | 0.036             |
| 1996-2005   | 0.0128         | 0.0098               | -0.0019                   | 0.0084                    | 0.0030         | 0.2388                         | -0.0456                                     | 0.0411        | 0.049             | 0.03              |
| 2006-2015   | 0.0078         | 0.0068               | 0.0055                    | 0.0014                    | 0.0009         | 0.1257                         | 0.1011                                      | 0.0544        | 0.058             | 0.027             |
| 2016-2022   | 0.0088         | 0.0080               | 0.0207                    | 0.0013                    | 0.0008         | 0.1365                         | 0.3529                                      | 0.0585        | 0.054             | 0.025             |
| 1935-1940   | 0.0134         | 0.0133               | 0.0170                    | -0.0048                   | 0.0001         | 0.1240                         | 0.1585                                      | 0.1071        | 0.123             | 0.062             |
| 1941-1945   | 0.0271         | 0.0269               | 0.0208                    | 0.0068                    | 0.0002         | 0.4651                         | 0.3605                                      | 0.0577        | 0.065             | 0.031             |
| 1946-1950   | 0.0079         | 0.0072               | 0.0030                    | 0.0051                    | 0.0007         | 0.1392                         | 0.0576                                      | 0.0519        | 0.047             | 0.03              |
| 1951-1955   | 0.0150         | 0.0137               | 0.0021                    | 0.0128                    | 0.0012         | 0.4218                         | 0.0636                                      | 0.0326        | 0.034             | 0.019             |
| 1956-1960   | 0.0092         | 0.0071               | -0.0061                   | 0.0152                    | 0.0021         | 0.2089                         | -0.1803                                     | 0.0339        | 0.035             | 0.021             |
| 1961-1965   | 0.0135         | 0.0110               | 0.0152                    | -0.0012                   | 0.0025         | 0.2671                         | 0.3691                                      | 0.0412        | 0.044             | 0.034             |
| 1966-1970   | 0.0091         | 0.0046               | -0.0019                   | 0.0084                    | 0.0044         | 0.0784                         | -0.0316                                     | 0.0593        | 0.056             | 0.039             |
| 1971-1975   | 0.0046         | -0.0001              | 0.0055                    | 0.0014                    | 0.0047         | -0.0014                        | 0.0776                                      | 0.0708        | 0.069             | 0.038             |
| 1976-1980   | 0.0240         | 0.0177               | 0.0207                    | 0.0013                    | 0.0063         | 0.3084                         | 0.3590                                      | 0.0575        | 0.064             | 0.031             |
| 1981-1985   | 0.0175         | 0.0093               | -0.0001                   | 0.0172                    | 0.0082         | 0.2004                         | -0.0029                                     | 0.0462        | 0.05              | 0.033             |
| 1986-1990   | 0.0081         | 0.0026               | -0.0106                   | 0.0183                    | 0.0055         | 0.0463                         | -0.1886                                     | 0.0561        | 0.053             | 0.036             |
| 1991-1995   | 0.0172         | 0.0137               | 0.0106                    | 0.0065                    | 0.0035         | 0.4212                         | 0.3277                                      | 0.0325        | 0.053             | 0.034             |
| 1996-2000   | 0.0114         | 0.0072               | 0.0021                    | 0.0109                    | 0.0042         | 0.1762                         | 0.0514                                      | 0.0410        | 0.047             | 0.033             |
| 2001-2005   | 0.0142         | 0.0124               | 0.0088                    | 0.0052                    | 0.0018         | 0.2986                         | 0.2113                                      | 0.0416        | 0.05              | 0.028             |
| 2006-2010   | 0.0095         | 0.0077               | 0.0057                    | 0.0036                    | 0.0018         | 0.1156                         | 0.0856                                      | 0.0666        | 0.065             | 0.028             |
| 2011-2015   | 0.0060         | 0.0060               | -0.0029                   | 0.0101                    | 0.0000         | 0.1532                         | -0.0735                                     | 0.0390        | 0.049             | 0.024             |
| 2016-2022   | 0.0088         | 0.0080               | 0.0055                    | 0.0047                    | 0.0008         | 0.1365                         | 0.0940                                      | 0.0585        | 0.054             | 0.025             |

# Table 4: Continue...

| Period    | $s({R_f})$ | $t(\bar{R_m})$ | $t(\bar{_{R_m-{R_f}}})$ | $t(\bar{\hat{_{\gamma_1}}})$ | $t(\bar{\hat{_{\gamma_0}}})$ | ${\rho_m }({R_m})$ | ${\rho_m }({R_m-{R_f}})$ | ${\rho_m }({\hat{_{\gamma_1}}})$ | ${\rho_m }({\hat {_{\gamma_0}}})$ | ${\rho_m }({R_f})$ |
|-------------|-----------|------------|-----------|----------|---------|-----------|--------------|------------|-------------|-------------|
| 1935-2022 | 0.0025     | 6.19           | 4.88                    | 3.07                         | 6.62                         | 0.19               | 0.19                     | 0.09                             | 0.09                              | 0.97               |
| 1935-1945 | 0.0002     | 2.55           | 2.54                    | 2.14                         | 0.11                         | -0.06              | -0.06                    | -0.04                            | 0.05                              | 0.63               |
| 1946-1955 | 0.0004     | 2.89           | 2.65                    | 0.68                         | 3.84                         | 0.08               | 0.08                     | 0.07                             | 0.1                               | 0.87               |
| 1956-1965 | 0.0007     | 3.31           | 2.63                    | 1.21                         | 2.64                         | 0.12               | 0.13                     | 0.2                              | 0.36                              | 0.74               |
| 1966-1975 | 0.0012     | 1.15           | 0.38                    | 0.32                         | 1.4                          | 0.17               | 0.18                     | 0.1                              | 0.12                              | 0.83               |
| 1976-1985 | 0.0025     | 4.36           | 2.81                    | 1.94                         | 3.08                         | 0.11               | 0.13                     | 0.23                             | 0.14                              | 0.9                |
| 1986-1995 | 0.0014     | 3.02           | 1.94                    | 0.01                         | 3.79                         | 0.22               | 0.22                     | 0.3                              | 0.02                              | 0.92               |
| 1996-2005 | 0.0015     | 3.41           | 2.61                    | 1.22                         | 2.89                         | 0.18               | 0.19                     | 0.1                              | -0.06                             | 0.96               |
| 2006-2015 | 0.0015     | 1.56           | 1.38                    | 0.27                         | 2.82                         | 0.21               | 0.21                     | 0.16                             | 0.07                              | 0.98               |
| 2016-2022 | 0.0008     | 1.38           | 1.25                    | 0.94                         | 1.69                         | -0.06              | -0.06                    | -0.07                            | -0.02                             | 0.89               |
| 1935-1940 | 0.0002     | 1.06           | 1.05                    | 1.17                         | -0.65                        | -0.12              | -0.12                    | -0.09                            | -0.01                             | 0.43               |
| 1941-1945 | 0.0001     | 3.63           | 3.61                    | 2.46                         | 1.67                         | 0.15               | 0.15                     | 0.15                             | 0.25                              | 0.67               |
| 1946-1950 | 0.0003     | 1.18           | 1.08                    | 0.49                         | 1.32                         | 0.08               | 0.08                     | 0.03                             | 0.17                              | 0.88               |
| 1951-1955 | 0.0004     | 3.56           | 3.25                    | 0.47                         | 5.13                         | -0.02              | -0.02                    | 0.1                              | -0.04                             | 0.74               |
| 1956-1960 | 0.0007     | 2.1            | 1.61                    | -1.37                        | 5.67                         | 0.11               | 0.13                     | 0.16                             | 0.14                              | 0.66               |
| 1961-1965 | 0.0006     | 2.54           | 2.07                    | 2.65                         | -0.27                        | 0.11               | 0.11                     | 0.15                             | 0.36                              | 0.81               |
| 1966-1970 | 0.0009     | 1.19           | 0.6                     | -0.26                        | 1.67                         | 0.21               | 0.22                     | 0.14                             | 0.14                              | 0.84               |
| 1971-1975 | 0.0014     | 0.5            | -0.01                   | 0.62                         | 0.28                         | 0.12               | 0.12                     | 0.06                             | 0.11                              | 0.83               |
| 1976-1980 | 0.0024     | 3.23           | 2.38                    | 2.52                         | 0.33                         | 0.04               | 0.04                     | 0.19                             | 0.16                              | 0.83               |
| 1981-1985 | 0.0022     | 2.93           | 1.53                    | -0.02                        | 4.02                         | 0.21               | 0.24                     | 0.22                             | 0.04                              | 0.88               |
| 1986-1990 | 0.0011     | 1.12           | 0.36                    | -1.54                        | 3.89                         | 0.21               | 0.21                     | 0.31                             | -0.1                              | 0.79               |
| 1991-1995 | 0.001      | 4.1            | 3.28                    | 1.56                         | 1.46                         | 0.22               | 0.22                     | 0.24                             | 0.13                              | 0.87               |
| 1996-2000 | 0.0005     | 2.16           | 1.36                    | 0.34                         | 2.56                         | 0.13               | 0.14                     | 0.11                             | 0.02                              | 0.49               |
| 2001-2005 | 0.0011     | 2.64           | 2.31                    | 1.35                         | 1.44                         | 0.18               | 0.19                     | 0.07                             | -0.05                             | 0.84               |
| 2006-2010 | 0.0018     | 1.11           | 0.89                    | 0.68                         | 0.98                         | 0.31               | 0.32                     | 0.26                             | 0.04                              | 0.97               |
| 2011-2015 | 0          | 1.19           | 1.19                    | -0.45                        | 3.19                         | -0.1               | -0.1                     | -0.02                            | 0.03                              | 0.48               |
| 2016-2022 | 0.0008     | 1.38           | 1.25                    | 0.94                         | 1.69                         | -0.06              | -0.06                    | -0.07                            | -0.02                             | 0.89               |

Analysis of replication result of Table 4

The Table 4 in the original paper is about the analysis of the behavior
of the market. Comparing the replication results with the original paper
when the periods are the same, most of the statistics are quite similar.
This suggests that the replication is quite successful.

If CAPM is valid, then $E({\gamma_0})=E({R_0})$, where $E({R_0})$ is the
expected return of zero-beta portfolio. Besides, the excess return of
the market portfolio is equal to the expectation of ${\gamma_1}$.
Specifically, the zero-beta portfolio is a risk-free asset when
applicable. However, in the table 4, we could see that in the majority
of time periods, ${\gamma_0}$ is larger than risk-free rate. The only
exception is in the period of 1970s, during which America economy
experienced an economy with high inflation and high unemployment rate.

The risk premium of the market portfolio is 1% for the whole sample
period. The periods during which the risk premium is substantially
larger than the average level are related to the bubble periods. For
example, the period 1941 to 1945 corresponds to the World War II.
Between 1976 and 1985 is just before the Black Monday in 1987.

Another pattern which is also observed in the Table 4 is that both the
values of ${\bar{R_m - R_f}}$ and ${\bar{\hat{\gamma_1}}}$ decline from
the pre-crisis period to post-crisis. On the other hand, the Sharpe
ratio of the market portfolio becomes relatively stable occasionally. It
would climb to a relatively high level before bubble or crisis (such as
0.465 in years 1941 to 1945 and 0.422 for years between 1951 to 1955).
For other time, the value is roughly around 0.14.

# Acknowledgement

This report is prepared by both efforts of both the group members and
have no conflict of interest.

# Reference

Fama, E. F., & MacBeth, J. D. (1973). Risk, return, and equilibrium:
Empirical tests. Journal of political economy, 81(3), 607-636.
